name: Weekly Scraper

permissions:
  contents: write  

on:
  workflow_dispatch:  
  schedule:
    - cron: '0 0 * * 0'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.9'  

      - name: Install necessary packages
        run: pip install requests beautifulsoup4 pandas

      - name: List files  
        run: ls -R

      - name: Run scraper
        run: python ./scraper.py || { echo 'Script failed'; exit 1; }

      - name: Commit and push CSV file
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add products.csv
          git commit -m "Update products CSV" || echo "No changes to commit"
          git push
