name: Weekly Scraper

permissions:
  contents: write  # Allow the action to commit changes

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 0 * * 0'  # This runs every Sunday at midnight

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest version
        with:
          python-version: '3.9'  # Specify the Python version you want

      - name: Install necessary packages
        run: pip install requests beautifulsoup4 pandas

      - name: List files  # Debugging step
        run: ls -R

      - name: Run seafood scraper
        run: python ./seafood.py || { echo 'Script failed'; exit 1; }  # Running the correct file

      - name: Commit and push CSV file
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add products.csv
          git commit -m "Update products CSV" || echo "No changes to commit"
          git push
